name: everything
description: A Flutter-based productivity app for managing communications, calendars, and events.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.0
  sqflite: ^2.3.0
  path: ^1.9.0
  http: ^1.2.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.25.0
  flutter_secure_storage: ^9.2.0
  shared_preferences: ^2.2.0
  flutter_bloc: ^8.1.0
  intl: ^0.20.2
  share_plus: ^7.2.0
  path_provider: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  bloc_test: ^9.1.0

flutter:
  uses-material-design: true
